In [1]:
import requests
import pandas as pd

In [3]:
df0 = pd.read_csv("df_city_bikes.csv")
df0

,Unnamed: 0,Station ID,Name,Latitude,Longitude,Free Bikes,Availability
0,0,013416a343d71698cbfdea3581cd7302,SE Spokane at Oaks Park Way,45.465082,-122.661689,4,0.800000
1,1,013f3d702a2aa7c3898a54be63c5a021,Cleveland High School,45.498947,-122.637669,1,0.111111
2,2,019f27f78942837d1f517001804c351c,Millar Library,45.511454,-122.685640,0,0.000000
3,3,043399190499833843cf731ea5114fae,SW 10th at Columbia,45.515444,-122.684675,7,0.700000
4,4,0718c230d62c6b77acb7c5b91952ccd2,N Vancouver at Alberta,45.559410,-122.668523,0,0.000000
...,...,...,...,...,...,...,...
243,243,fc384e1781ccea99cbc6075769be1785,SE 17th Ave at Mall St,45.491114,-122.648666,9,1.000000
244,244,fce35a8ba9b028a7f14d7a041b62f017,North Lombard Street at Greeley Avenue,45.577077,-122.695579,0,0.000000
245,245,fd51ad5bbf138465fac3a76c2f3e9f6b,NW Johnson at Jamison Square,45.528637,-122.682019,11,0.916667
246,246,ff54bba5b85cda833a23610dfc64fddc,SE 37th at Gladstone,45.493337,-122.623397,0,0.000000
247,247,ffd6e574f4b43b41e1cf1aba17514ccf,SE 12th ave at SE Powell Blvd,45.500575,-122.653093,1,0.166667

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [33]:
dfa = []
for _, row in df0.iloc[:150].iterrows():
    url = "https://api.foursquare.com/v3/places/search?ll={}%2C{}&limit=50&radius=1000".format(row['Latitude'],row['Longitude'])
    
    headers = {
        "accept": "application/json",
        "Authorization": "fsq3t2s+ZH5BDPybgZlpbl10+GD753Y+e8pz6DzkI5W+hkE="
    }
    
    response = requests.get(url, headers=headers)
    dfa.append(response.json())

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [37]:
dfa[0]['results'][0]

{'fsq_id': '4e4d8b82149505fcf1260b4d',
 'categories': [{'id': 16032,
   'name': 'Park',
   'short_name': 'Park',
   'plural_name': 'Parks',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
    'suffix': '.png'}}],
 'chains': [],
 'closed_bucket': 'Unsure',
 'distance': 191,
 'geocodes': {'main': {'latitude': 45.464915, 'longitude': -122.663344},
  'roof': {'latitude': 45.464915, 'longitude': -122.663344}},
 'link': '/v3/places/4e4d8b82149505fcf1260b4d',
 'location': {'address': '1 SE Spokane St',
  'census_block': '410510001024025',
  'country': 'US',
  'cross_street': '',
  'dma': 'Portland, Or',
  'formatted_address': '1 SE Spokane St, Portland, OR 97202',
  'locality': 'Portland',
  'postcode': '97202',
  'region': 'OR'},
 'name': 'Sellwood Riverfront Park',
 'related_places': {'children': []},
 'timezone': 'America/Los_Angeles'}

In [17]:
list = []
statNameList = df0['Name'][:150]
nameIndex = -1
for item in dfa:
    nameIndex += 1
    for loca in item['results']:
        sl = []
        sl.append(loca['name'])
        sl.append(loca['distance'])
        sl.append(
        sl.append(statNameList[nameIndex])
        list.append(sl)

Put your parsed results into a DataFrame

In [19]:
df1 = pd.DataFrame(list, columns=['Name','Distance','Station Name'])

In [20]:
df1

Empty DataFrame
Columns: [Name, Distance, Station Name]
Index: []

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [41]:
dfa2 = []
for _, row in df0.iloc[:150].iterrows():
    url2 = "https://api.yelp.com/v3/businesses/search?categories=restaurants,bars,landmarks&latitude={}&longitude={}&limit=50&radius=1000&sortBy=ratings".format(row['Latitude'], row['Longitude'])
    
    headers2 = {
        "Authorization": "Bearer ZwpyAgyaE0Ylhh1weYuF4gVGDbo2o83eUC-Y4VI1Z-XpxGMG2US-glIYZKNT2XWXfjPOhGo79pF_q48XzYHM8bo37J1E8G1y4U1wWNDBkhDm02XZgxhVDP1_uJ6aZ3Yx"
    }
    response = requests.get(url2, headers=headers2)

    dfa2.append(response.json())

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [45]:
dfa2[0]

{'error': {'code': 'TRIAL_EXPIRED',
  'description': 'Your Trial has expired. Please upgrade to continue using the service. Visit https://www.yelp.com/developers/v3/manage_app or email at fusion@yelp.com to explore options.'}}

In [123]:
list = []
statNameList = df0['Name'][:150]
nameIndex = -1
for item in dfa2:
    nameIndex += 1
    for loca in item['businesses']:
        sl = []
        sl.append(loca['name'])
        sl.append(loca['distance'])
        sl.append(loca['rating'])
        sl.append(loca['review_count'])
        sl.append(loca['price'])
        sl.append(statNameList[nameIndex])
        list.append(sl)

[['De Binnenkomer', 599.4072940907039, 4.7, 'Alkmaar'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Alkmaar'],
 ['Daikichi', 54.04131208278735, 4.0, 'Alkmaar'],
 ['Burger King', 38.753209797124605, 3.0, 'Alkmaar'],
 ['Deli', 1009.748379483375, 4.8, 'Alkmaar'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Alkmaar'],
 ['De Buren', 1060.7939670377473, 4.1, 'Alkmaar'],
 ['King Sing', 212.2733144925375, 3.0, 'Alkmaar'],
 ['Aloha', 852.7449434363177, 4.0, 'Alkmaar'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Alkmaar'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Alkmaar'],
 ['Schots Restaurant Hielander', 1008.5839781538273, 3.8, 'Alkmaar'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Alkmaar'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Alkmaar'],
 ["Mojo's", 942.0027393749233, 5.0, 'Alkmaar'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Alkmaar'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Alkmaar'],
 ['Vito', 1485.8453538466451, 4.3, 'Alkmaar'],
 ["Abby's", 852.017140325663, 4.3, 'Alkmaar'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Alkmaar'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Alkmaar'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Alkmaar'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Alkmaar'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Alkmaar'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Alkmaar'],
 ['Pizzeria Ristorante La Famiglia', 499.8180731679537, 4.0, 'Alkmaar'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Alkmaar'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Alkmaar'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Alkmaar'],
 ['SuperThai Restaurant ', 749.6106910535735, 3.3, 'Alkmaar'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Alkmaar'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Alkmaar'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Alkmaar'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Alkmaar'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Alkmaar'],
 ['Granada Grand Cafe & Restaurant', 597.1834813755764, 5.0, 'Alkmaar'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Alkmaar'],
 ['Kunchai', 994.5218072237367, 4.5, 'Alkmaar'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Alkmaar'],
 ['Moeke', 484.4824365505958, 0.0, 'Alkmaar'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Alkmaar'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Alkmaar'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Alkmaar'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Alkmaar'],
 ['Taormina', 1149.6070313784464, 5.0, 'Alkmaar'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Alkmaar'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Alkmaar'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Alkmaar'],
 ['Subway', 861.8243738210845, 5.0, 'Alkmaar'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Alkmaar'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Amsterdam Noord'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Amsterdam Noord'],
 ['Daikichi', 54.04131208278735, 4.0, 'Amsterdam Noord'],
 ['Burger King', 38.753209797124605, 3.0, 'Amsterdam Noord'],
 ['Deli', 1009.748379483375, 4.8, 'Amsterdam Noord'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Amsterdam Noord'],
 ['De Buren', 1060.7939670377473, 4.1, 'Amsterdam Noord'],
 ['King Sing', 212.2733144925375, 3.0, 'Amsterdam Noord'],
 ['Aloha', 852.7449434363177, 4.0, 'Amsterdam Noord'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Amsterdam Noord'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Amsterdam Noord'],
 ['Schots Restaurant Hielander', 1008.5839781538273, 3.8, 'Amsterdam Noord'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Amsterdam Noord'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Amsterdam Noord'],
 ["Mojo's", 942.0027393749233, 5.0, 'Amsterdam Noord'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Amsterdam Noord'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Amsterdam Noord'],
 ['Vito', 1485.8453538466451, 4.3, 'Amsterdam Noord'],
 ["Abby's", 852.017140325663, 4.3, 'Amsterdam Noord'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Amsterdam Noord'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Amsterdam Noord'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Amsterdam Noord'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Amsterdam Noord'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Amsterdam Noord'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Amsterdam Noord'],
 ['Pizzeria Ristorante La Famiglia',
  499.8180731679537,
  4.0,
  'Amsterdam Noord'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Amsterdam Noord'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Amsterdam Noord'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Amsterdam Noord'],
 ['SuperThai Restaurant ', 749.6106910535735, 3.3, 'Amsterdam Noord'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Amsterdam Noord'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Amsterdam Noord'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Amsterdam Noord'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Amsterdam Noord'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Amsterdam Noord'],
 ['Granada Grand Cafe & Restaurant',
  597.1834813755764,
  5.0,
  'Amsterdam Noord'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Amsterdam Noord'],
 ['Kunchai', 994.5218072237367, 4.5, 'Amsterdam Noord'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Amsterdam Noord'],
 ['Moeke', 484.4824365505958, 0.0, 'Amsterdam Noord'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Amsterdam Noord'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Amsterdam Noord'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Amsterdam Noord'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Amsterdam Noord'],
 ['Taormina', 1149.6070313784464, 5.0, 'Amsterdam Noord'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Amsterdam Noord'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Amsterdam Noord'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Amsterdam Noord'],
 ['Subway', 861.8243738210845, 5.0, 'Amsterdam Noord'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Amsterdam Noord'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Hoogeveen'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Hoogeveen'],
 ['Daikichi', 54.04131208278735, 4.0, 'Hoogeveen'],
 ['Burger King', 38.753209797124605, 3.0, 'Hoogeveen'],
 ['Deli', 1009.748379483375, 4.8, 'Hoogeveen'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Hoogeveen'],
 ['De Buren', 1060.7939670377473, 4.1, 'Hoogeveen'],
 ['King Sing', 212.2733144925375, 3.0, 'Hoogeveen'],
 ['Aloha', 852.7449434363177, 4.0, 'Hoogeveen'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Hoogeveen'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Hoogeveen'],
 ['Schots Restaurant Hielander', 1008.5839781538273, 3.8, 'Hoogeveen'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Hoogeveen'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Hoogeveen'],
 ["Mojo's", 942.0027393749233, 5.0, 'Hoogeveen'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Hoogeveen'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Hoogeveen'],
 ['Vito', 1485.8453538466451, 4.3, 'Hoogeveen'],
 ["Abby's", 852.017140325663, 4.3, 'Hoogeveen'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Hoogeveen'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Hoogeveen'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Hoogeveen'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Hoogeveen'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Hoogeveen'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Hoogeveen'],
 ['Pizzeria Ristorante La Famiglia', 499.8180731679537, 4.0, 'Hoogeveen'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Hoogeveen'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Hoogeveen'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Hoogeveen'],
 ['SuperThai Restaurant ', 749.6106910535735, 3.3, 'Hoogeveen'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Hoogeveen'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Hoogeveen'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Hoogeveen'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Hoogeveen'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Hoogeveen'],
 ['Granada Grand Cafe & Restaurant', 597.1834813755764, 5.0, 'Hoogeveen'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Hoogeveen'],
 ['Kunchai', 994.5218072237367, 4.5, 'Hoogeveen'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Hoogeveen'],
 ['Moeke', 484.4824365505958, 0.0, 'Hoogeveen'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Hoogeveen'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Hoogeveen'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Hoogeveen'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Hoogeveen'],
 ['Taormina', 1149.6070313784464, 5.0, 'Hoogeveen'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Hoogeveen'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Hoogeveen'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Hoogeveen'],
 ['Subway', 861.8243738210845, 5.0, 'Hoogeveen'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Hoogeveen'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Zoetermeer Driemanspolder'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Zoetermeer Driemanspolder'],
 ['Daikichi', 54.04131208278735, 4.0, 'Zoetermeer Driemanspolder'],
 ['Burger King', 38.753209797124605, 3.0, 'Zoetermeer Driemanspolder'],
 ['Deli', 1009.748379483375, 4.8, 'Zoetermeer Driemanspolder'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Zoetermeer Driemanspolder'],
 ['De Buren', 1060.7939670377473, 4.1, 'Zoetermeer Driemanspolder'],
 ['King Sing', 212.2733144925375, 3.0, 'Zoetermeer Driemanspolder'],
 ['Aloha', 852.7449434363177, 4.0, 'Zoetermeer Driemanspolder'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Zoetermeer Driemanspolder'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Zoetermeer Driemanspolder'],
 ['Schots Restaurant Hielander',
  1008.5839781538273,
  3.8,
  'Zoetermeer Driemanspolder'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Zoetermeer Driemanspolder'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Zoetermeer Driemanspolder'],
 ["Mojo's", 942.0027393749233, 5.0, 'Zoetermeer Driemanspolder'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Zoetermeer Driemanspolder'],
 ['Horecacentrum De Studio',
  516.498093746401,
  5.0,
  'Zoetermeer Driemanspolder'],
 ['Vito', 1485.8453538466451, 4.3, 'Zoetermeer Driemanspolder'],
 ["Abby's", 852.017140325663, 4.3, 'Zoetermeer Driemanspolder'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Zoetermeer Driemanspolder'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Zoetermeer Driemanspolder'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Zoetermeer Driemanspolder'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Zoetermeer Driemanspolder'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Zoetermeer Driemanspolder'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Zoetermeer Driemanspolder'],
 ['Pizzeria Ristorante La Famiglia',
  499.8180731679537,
  4.0,
  'Zoetermeer Driemanspolder'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Zoetermeer Driemanspolder'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Zoetermeer Driemanspolder'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Zoetermeer Driemanspolder'],
 ['SuperThai Restaurant ',
  749.6106910535735,
  3.3,
  'Zoetermeer Driemanspolder'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Zoetermeer Driemanspolder'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Zoetermeer Driemanspolder'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Zoetermeer Driemanspolder'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Zoetermeer Driemanspolder'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Zoetermeer Driemanspolder'],
 ['Granada Grand Cafe & Restaurant',
  597.1834813755764,
  5.0,
  'Zoetermeer Driemanspolder'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Zoetermeer Driemanspolder'],
 ['Kunchai', 994.5218072237367, 4.5, 'Zoetermeer Driemanspolder'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Zoetermeer Driemanspolder'],
 ['Moeke', 484.4824365505958, 0.0, 'Zoetermeer Driemanspolder'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Zoetermeer Driemanspolder'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Zoetermeer Driemanspolder'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Zoetermeer Driemanspolder'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Zoetermeer Driemanspolder'],
 ['Taormina', 1149.6070313784464, 5.0, 'Zoetermeer Driemanspolder'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Zoetermeer Driemanspolder'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Zoetermeer Driemanspolder'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Zoetermeer Driemanspolder'],
 ['Subway', 861.8243738210845, 5.0, 'Zoetermeer Driemanspolder'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Zoetermeer Driemanspolder'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Veenendaal Centrum'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Veenendaal Centrum'],
 ['Daikichi', 54.04131208278735, 4.0, 'Veenendaal Centrum'],
 ['Burger King', 38.753209797124605, 3.0, 'Veenendaal Centrum'],
 ['Deli', 1009.748379483375, 4.8, 'Veenendaal Centrum'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Veenendaal Centrum'],
 ['De Buren', 1060.7939670377473, 4.1, 'Veenendaal Centrum'],
 ['King Sing', 212.2733144925375, 3.0, 'Veenendaal Centrum'],
 ['Aloha', 852.7449434363177, 4.0, 'Veenendaal Centrum'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Veenendaal Centrum'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Veenendaal Centrum'],
 ['Schots Restaurant Hielander',
  1008.5839781538273,
  3.8,
  'Veenendaal Centrum'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Veenendaal Centrum'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Veenendaal Centrum'],
 ["Mojo's", 942.0027393749233, 5.0, 'Veenendaal Centrum'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Veenendaal Centrum'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Veenendaal Centrum'],
 ['Vito', 1485.8453538466451, 4.3, 'Veenendaal Centrum'],
 ["Abby's", 852.017140325663, 4.3, 'Veenendaal Centrum'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Veenendaal Centrum'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Veenendaal Centrum'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Veenendaal Centrum'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Veenendaal Centrum'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Veenendaal Centrum'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Veenendaal Centrum'],
 ['Pizzeria Ristorante La Famiglia',
  499.8180731679537,
  4.0,
  'Veenendaal Centrum'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Veenendaal Centrum'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Veenendaal Centrum'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Veenendaal Centrum'],
 ['SuperThai Restaurant ', 749.6106910535735, 3.3, 'Veenendaal Centrum'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Veenendaal Centrum'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Veenendaal Centrum'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Veenendaal Centrum'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Veenendaal Centrum'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Veenendaal Centrum'],
 ['Granada Grand Cafe & Restaurant',
  597.1834813755764,
  5.0,
  'Veenendaal Centrum'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Veenendaal Centrum'],
 ['Kunchai', 994.5218072237367, 4.5, 'Veenendaal Centrum'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Veenendaal Centrum'],
 ['Moeke', 484.4824365505958, 0.0, 'Veenendaal Centrum'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Veenendaal Centrum'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Veenendaal Centrum'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Veenendaal Centrum'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Veenendaal Centrum'],
 ['Taormina', 1149.6070313784464, 5.0, 'Veenendaal Centrum'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Veenendaal Centrum'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Veenendaal Centrum'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Veenendaal Centrum'],
 ['Subway', 861.8243738210845, 5.0, 'Veenendaal Centrum'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Veenendaal Centrum'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Sneek'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Sneek'],
 ['Daikichi', 54.04131208278735, 4.0, 'Sneek'],
 ['Burger King', 38.753209797124605, 3.0, 'Sneek'],
 ['Deli', 1009.748379483375, 4.8, 'Sneek'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Sneek'],
 ['De Buren', 1060.7939670377473, 4.1, 'Sneek'],
 ['King Sing', 212.2733144925375, 3.0, 'Sneek'],
 ['Aloha', 852.7449434363177, 4.0, 'Sneek'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Sneek'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Sneek'],
 ['Schots Restaurant Hielander', 1008.5839781538273, 3.8, 'Sneek'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Sneek'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Sneek'],
 ["Mojo's", 942.0027393749233, 5.0, 'Sneek'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Sneek'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Sneek'],
 ['Vito', 1485.8453538466451, 4.3, 'Sneek'],
 ["Abby's", 852.017140325663, 4.3, 'Sneek'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Sneek'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Sneek'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Sneek'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Sneek'],
 ['Petershoek Café', 90.49918999393957, 0.0, 'Sneek'],
 ['Burgers & Zo', 566.070511391871, 3.5, 'Sneek'],
 ['Pizzeria Ristorante La Famiglia', 499.8180731679537, 4.0, 'Sneek'],
 ['Heeren van Sonoy', 811.7969541676354, 3.0, 'Sneek'],
 ['Gulden Vlies', 749.6198242086455, 4.0, 'Sneek'],
 ['La Cubanita Alkmaar', 1019.1139257354848, 5.0, 'Sneek'],
 ['SuperThai Restaurant ', 749.6106910535735, 3.3, 'Sneek'],
 ['Café-Bar Odeon', 1117.6786219087742, 4.0, 'Sneek'],
 ['Grand Café Klunder', 491.1964571528282, 0.0, 'Sneek'],
 ['1480 Food Bar', 1019.4541370951409, 4.0, 'Sneek'],
 ['Restaurant Tapas &', 1057.2459116972116, 5.0, 'Sneek'],
 ['Happy Italy', 518.4117475871739, 3.3, 'Sneek'],
 ['Granada Grand Cafe & Restaurant', 597.1834813755764, 5.0, 'Sneek'],
 ['Proeflokaal De Boom', 942.184391949158, 0.0, 'Sneek'],
 ['Kunchai', 994.5218072237367, 4.5, 'Sneek'],
 ['Cafe De Pilaren', 1085.9413393183647, 5.0, 'Sneek'],
 ['Moeke', 484.4824365505958, 0.0, 'Sneek'],
 ['De Amstelhoek', 967.9020076874574, 4.0, 'Sneek'],
 ['Il Colosseo', 738.3859911669595, 5.0, 'Sneek'],
 ['Rue de la Plume', 789.023446360917, 5.0, 'Sneek'],
 ["'t Friethuys", 937.8352468571736, 5.0, 'Sneek'],
 ['Taormina', 1149.6070313784464, 5.0, 'Sneek'],
 ['Ristobar Italica', 1083.0744620729238, 2.4, 'Sneek'],
 ['Le Bon', 1008.7088239418918, 4.0, 'Sneek'],
 ['De Bonte Bengel', 574.7221520255662, 2.8, 'Sneek'],
 ['Subway', 861.8243738210845, 5.0, 'Sneek'],
 ['Cafe Bali', 920.3244724023469, 3.7, 'Sneek'],
 ['De Binnenkomer', 599.4072940907039, 4.7, 'Voorburg'],
 ['Vers Eten & Drinken', 77.34336015072499, 4.5, 'Voorburg'],
 ['Daikichi', 54.04131208278735, 4.0, 'Voorburg'],
 ['Burger King', 38.753209797124605, 3.0, 'Voorburg'],
 ['Deli', 1009.748379483375, 4.8, 'Voorburg'],
 ['Anne & Max', 1050.9389047964175, 4.8, 'Voorburg'],
 ['De Buren', 1060.7939670377473, 4.1, 'Voorburg'],
 ['King Sing', 212.2733144925375, 3.0, 'Voorburg'],
 ['Aloha', 852.7449434363177, 4.0, 'Voorburg'],
 ['Stadsstrand de Kade', 620.6513341917654, 5.0, 'Voorburg'],
 ['Alkmaars Koffiehuis', 723.9196172713763, 5.0, 'Voorburg'],
 ['Schots Restaurant Hielander', 1008.5839781538273, 3.8, 'Voorburg'],
 ['Saladebar Oogst', 479.2986157354422, 5.0, 'Voorburg'],
 ["Irish Pub Gunnery's", 1101.3625315377635, 5.0, 'Voorburg'],
 ["Mojo's", 942.0027393749233, 5.0, 'Voorburg'],
 ['Het Grand Cafeetje', 935.7281656931732, 4.0, 'Voorburg'],
 ['Horecacentrum De Studio', 516.498093746401, 5.0, 'Voorburg'],
 ['Vito', 1485.8453538466451, 4.3, 'Voorburg'],
 ["Abby's", 852.017140325663, 4.3, 'Voorburg'],
 ['Proeflokaal Bregje', 525.2107427451322, 2.3, 'Voorburg'],
 ['restaurant zegels', 744.6440355872974, 4.7, 'Voorburg'],
 ['Meat & Co', 1020.6355087576528, 4.3, 'Voorburg'],
 ['Fresh Food', 93.87041630226362, 0.0, 'Voorburg'],

Put your parsed results into a DataFrame

In [129]:
df2 = pd.DataFrame(list, columns=['Name','Distance','Rating','Station Name'])

In [127]:
df2

                     Name     Distance  rating Station Name
0          De Binnenkomer   599.407294     4.7      Alkmaar
1     Vers Eten & Drinken    77.343360     4.5      Alkmaar
2                Daikichi    54.041312     4.0      Alkmaar
3             Burger King    38.753210     3.0      Alkmaar
4                    Deli  1009.748379     4.8      Alkmaar
...                   ...          ...     ...          ...
7495     Ristobar Italica  1083.074462     2.4   Ravenstein
7496               Le Bon  1008.708824     4.0   Ravenstein
7497      De Bonte Bengel   574.722152     2.8   Ravenstein
7498               Subway   861.824374     5.0   Ravenstein
7499            Cafe Bali   920.324472     3.7   Ravenstein

[7500 rows x 4 columns]

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

I chose yelp, because it had a rating with the restaurants and foursquare did not, as well as the fact that yelp gave more answers.

On a later note, my free trial to yelp is expired so I can't use it, and will now move over to foursquare.

Get the top 10 restaurants according to their rating

In [131]:
df_sorted = df2.sort_values(by='Rating', ascending=False)

In [137]:
df_sorted.head(10)

,Name,Distance,Rating,Station Name
5128,La Cubanita Alkmaar,1019.113926,5.0,Hoorn
4478,La Cubanita Alkmaar,1019.113926,5.0,Utrecht Terwijde
1733,Restaurant Tapas &,1057.245912,5.0,Eindhoven Centraal zuidzijde (centrum)
4491,Il Colosseo,738.385991,5.0,Utrecht Terwijde
1735,Granada Grand Cafe & Restaurant,597.183481,5.0,Eindhoven Centraal zuidzijde (centrum)
4488,Cafe De Pilaren,1085.941339,5.0,Utrecht Terwijde
4485,Granada Grand Cafe & Restaurant,597.183481,5.0,Utrecht Terwijde
1738,Cafe De Pilaren,1085.941339,5.0,Eindhoven Centraal zuidzijde (centrum)
4483,Restaurant Tapas &,1057.245912,5.0,Utrecht Terwijde
1741,Il Colosseo,738.385991,5.0,Eindhoven Centraal zuidzijde (centrum)

In [142]:
df2.to_csv('yelp_data.csv')